# -*- coding: utf-8 -*-
"""
/***************************************************************************
 example
                                 A QGIS plugin
 just an example
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-28
        copyright            : (C) 2021 by Josep Andreu Sabate
        email                : josep.andreu@e-campus.uab.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load example class from file example.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .example import example
    return example(iface)
