# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WidgetExample
                                 A QGIS plugin
 Testing QGIS costum widgets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-05
        copyright            : (C) 2021 by Josep Andreu
        email                : josep.andreu@e-campus.uab.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WidgetExample class from file WidgetExample.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .widget_example import WidgetExample
    return WidgetExample(iface)
